apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vault
          restartPolicy: OnFailure
          containers:
          - name: vault-backup 
            image: nietxan/vault-backup:latest
            securityContext:
              capabilities:
                add: ["IPC_LOCK"]
            env:
            - name: VAULT_ADDR
              value: "http://vault-active.vault.svc.cluster.local:8200"
            - name: S3_BUCKET
              value: "vault-backups-bucket"
            command: ["source /scripts/backup.sh"]
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
                ephemeral-storage: "512Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
                ephemeral-storage: "1024Mi"
            volumeMounts:
              - name: tmp 
                mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir:
                sizeLimit: "1024Mi"
